### ISSUE TITLE
Blueharvest should have an installer package

### ISSUE THREAD

**Issue by ybotspawn** [DIOS-Tech/BlueHarvest#18]
Windows
Linux

**Comment by frankhale** [comment]
Not sure how this can be implemented since Blue Harvest is an ASP.NET Web API + MVC application. There are a lot of prerequisites that would be a nightmare to try to figure out how to check. Why not instead provide good instructions on how to set this up? It should be straight forward for anyone familiar with working with ASP.NET / IIS / SQL Server stuff.

**Comment by frankhale** [comment]
Closing because it would its beyond the scope of this project to put together an installer for a web app, web api, database and other infrastructure due to time and man power considerations.

**Comment by frankhale** [comment]
We'll just need to put together some instructions on how to use this in the README.
